
server.port: 9100
server.servlet.context-path: /api

BASE_LOCATION: D:\java\code\毕设\java_shop
DB_NAME: shop

  #BASE_LOCATION: C:\Users\Administrator\Desktop\java-shop
  #DB_NAME: java_shop


File:
  uploadPath: ${BASE_LOCATION}\server\upload

mybatis:
  configuration:
    map-underscore-to-camel-case: true

  # 数据库配置
  # todo 需替换配置
spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  mvc:
    # URL响应地址（Springboot默认为/**)
    static-path-pattern: /upload/**
    web:
      resources:
        # 静态文件地址，保留官方内容后，进行追加
        static-locations: classpath:atic,classpath:/public,classpath:/resources,classpath:/META-INF/resources,file:upload
    redis:
      #超时时间
      timeout: 10000ms
      #服务器地址
      host: localhost
      #服务器端口
      port: 6379
      #数据库
      database: 1
      #密码
      password: root
      lettuce:
      pool:
      #最大连接数，默认8
      max-active: 1024
      #最大连接阻塞等待时间，默认-1
      max-wait: 10000ms

      #最大空闲连接
      max-idle: 200
      #最小空闲连接
      min-idle: 5
    rabbitmq:
      host: localhost
      username: guest
      password: guest
      virtual-host: /
      port: 5672
      listner:
        simple:
          #消费者最小数量
          concurrency: 10
          #消费者最大数量
          max-concurrency: 10
          #限制消费者每次只处理一条消息，处理完再继续下一条消息
          prefetch: 1
        template:
          retry:
            #发布重试，默认false
            enabled: true
            #重试时间，默认1000ms
            initial-interval: 1000ms
            #重试最大次数，默认3次
            max-attempts: 3
            #最大重试间隔时间
            max-interval: 10000ms
            #重试的间隔乘数，比如配2。0  第一等10s 第二次等20s 第三次等40s
            multiplier: 1